config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users

  root to: 'personalities#index'
  resources :personalities do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :destroy, :edit, :update] do
    resources :personality_reviews, only: [:new, :create]
  end

  resources :users, only: [:show]

  get "index_gigs", to: "bookings#index_gigs", as: 'index_gigs'
  # do
  #   resources :doses, only: [:new, :create]
  # end
  # resources :doses, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :personality
  has_many :user_reviews
  has_many :personality_reviews, dependent: :destroy

  def calc_total_price
    hours = (self.end_date - self.start_date) / 3600
    (hours.to_f * self.personality.price_hour.to_f).round
  end
end

app/models/personality.rb
class Personality < ApplicationRecord
  belongs_to :user
  has_many :bookings
end

app/models/personality_review.rb
class PersonalityReview < ApplicationRecord
  belongs_to :booking

  validates :comment, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :personalities

  validates :first_name, :last_name, :location, :language, :phone, :birthdate, :image_url, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @personality = Personality.find(params[:personality_id])
    @bookings = @personality.bookings
  end

  def create
    @personality = Personality.find(params[:personality_id])
    @booking = Booking.new(booking_params)
    @booking.personality = @personality
    @booking.user = current_user
    @booking.status = nil
    if @booking.start_date && @booking.end_date
      @hours = (@booking.end_date - @booking.start_date) / 3600
      @booking.total_price = (@hours.to_f * @personality.price_hour.to_f).round
    else
      @booking.value = 0
    end
    if @booking.save
      redirect_to bookings_path
    else
      redirect_to personalities_path
    end
  end

  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  def index_gigs
    @personalities = current_user.personalities
    @my_bookings = Booking.where(personality_id: @personalities.pluck(:id))
  end

  def show
    set_booking
    @personality = @booking.personality
  end

  def edit
    set_booking
  end

  def update
    set_booking
    if params[:commit] == 'Confirm'
      @booking.update(status: true)
      redirect_to index_gigs_path
    elsif params[:commit] == 'Decline'
      @booking.update(status: false)
      redirect_to index_gigs_path
    else
      @booking.update(booking_params)
      redirect_to bookings_path
    end
  end

  def destroy
    set_booking
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/personalities_controller.rb
class PersonalitiesController < ApplicationController
  def index
    @personalities = Personality.all
    if params[:query].present?
      sql_query = "users.first_name @@ :query OR users.location @@ :query"
      @personalities = Personality.where(sql_query, query: "%#{params[:query]}%")
      @personalities = Personality.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @personalities = Personality.all

    end
    if params[:sort]
      if params[:sort] == "name"
        @personalities = @personalities.order(name: :asc)
      elsif params[:sort] == "price"
        @personalities = @personalities.order(price_hour: :asc)
      else
        @personalities = @personalities.order(created_at: :desc)
      end

    end
  end

  def show
    @personality = Personality.find(params[:id])
    @booking = Booking.new(start_date: DateTime.now, end_date: DateTime.now + 1.hour, personality: @personality)
    @user_lat = @personality.user.geocode[0]
    @user_lng = @personality.user.geocode[1]

    @markers = [{ lat: @user_lat, lng: @user_lng }]
  end

  def new
    @personality = Personality.new
  end

  def create
    @personality = Personality.new(personality_params)
    @personality.user = current_user
    if @personality.save
      redirect_to personality_path(@personality)
    else
      render :new
    end
  end

  def edit
    @personality = Personality.find(params[:id])
  end

  def update
    @personality = Personality.find(params[:id])
    @personality.user = current_user
    if @personality.update(personality_params)
      redirect_to personality_path(@personality)
    else
      render :new
    end
  end

  def destroy
    @personality = Personality.find(params[:id])
    @personality.destroy
    redirect_to personalities_path
  end

  private

  def personality_params
    # Not sure if I have to permit user_id here. Hard to test without current user login ready.
    params.require(:personality).permit(:name, :description, :price_hour, :image_url)
  end
end

app/controllers/personality_reviews_controller.rb
class PersonalityReviewsController < ApplicationController
  before_action :find_booking
  def new
    @personality_review = PersonalityReview.new
  end

  def create
    @personality_review = PersonalityReview.new(personality_review_params)
    @personality_review.booking = @booking

    if @personality_review.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private

  def find_booking
    @booking = Booking.find(params[:booking_id])
  end

  def personality_review_params
    params.require(:personality_review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
      <div class="booking-container p-3 mx-auto mt-5">

              <%= simple_form_for (@booking) do |f| %>
              <h6>From</h6>
              <%= f.datetime_local_field :start_date, class: 'date-field' %>
              <h6>To</h6>
              <%= f.datetime_local_field :end_date, class: 'date-field' %>
              <%= f.submit "Edit Booking", class: "btn btn-pink w-100"%>
          <% end%>
          </div>


        <%= link_to "Back", booking_path(@booking) %>

app/views/bookings/index.html.erb
<div class="tabs">

  <input type="radio" id="tab1" name="tab-control" checked>
  <input type="radio" id="tab4" name="tab-control">
  <ul>
    <li title="Gigs"><label for="tab1" role="button"><span>Upcoming Rentals</span></label></li>
    <li title="Reviews"><label for="tab4" role="button"><br><span>Past Rentals</span></label></li>
  </ul>

  <div class="slider"><div class="indicator"></div></div>
  <div class="content">
    <section>
      <h2>Upcoming Rentals</h2>
      <div class="cards-tab">
       <% @bookings.each do |booking| %>
       <% if booking.end_date > Time.now %>
       <div class="card-product tab" style="width: 300px">
            <img src="<%= booking.personality.image_url %>" />
            <div class="card-product-infos">
              <p style="color: #eb535b"><strong>  <%= booking.personality.user.first_name %>, <%= link_to booking.personality.name, booking_path(booking), style: 'color: #eb535b' %></strong></p>
              <p><%= booking.start_date.day %>/<%= booking.start_date.month %> for <strong><%=  ((booking.end_date - booking.start_date) / 3600).round %> hours </strong> </p>
              <p><% if booking.status == true %>
                  Booking Accepted ✔️
                 <% elsif booking.status == false %>
                  Booking cancelled ❌
                 <% else  %>
                  Booking Pending ⏱
                 <% end %>
              </p>
            </div>
        </div>
        <% end %>
        <% end %>
        </div>
    </section>
    <section>
      <h2>Past Rentals</h2>
       <div class="cards-tab">
       <% @bookings.each do |booking| %>
       <% if booking.end_date < Time.now %>
       <div class="card-product tab" style="width: 300px">
            <img src="<%= booking.personality.image_url %>" />
            <div class="card-product-infos">
              <p style="color: #eb535b"><strong><%= booking.personality.user.first_name %>, <%= link_to booking.personality.name, booking_path(booking), style: 'color: #eb535b' %></strong></p>
              <p><%= booking.start_date.day %>/<%= booking.start_date.month %> for <strong><%=  ((booking.end_date - booking.start_date) / 3600).round %> hours </strong> </p>
              <p><% if booking.status == true %>
                  Booking Accepted ✔️
                 <% elsif booking.status == false %>
                  Booking cancelled ❌
                 <% else  %>
                  Booking Pending ⏱
                 <% end %>
              </p>
            </div>
        </div>
        <% end %>
        <% end %>
        </div>
    </section>
  </div>
</div>

app/views/bookings/index_gigs.html.erb
<div class="tabs">

  <input type="radio" id="tab1" name="tab-control" checked>
  <input type="radio" id="tab4" name="tab-control">
  <ul>
    <li title="Gigs"><label for="tab1" role="button"><span>Upcoming Gigs</span></label></li>
    <li title="Reviews"><label for="tab4" role="button"><br><span>Past Gigs</span></label></li>
  </ul>

  <div class="slider"><div class="indicator"></div></div>
  <div class="content">
    <section>
      <h2>Upcoming</h2>
      <div class="cards-tab">
      <% @my_bookings.each do |mybooking| %>
      <% if mybooking.end_date > Time.now %>
      <div class="card-product tab" style="width: 300px">
          <img src="<%= mybooking.personality.image_url %>" />
          <div class="card-product-infos">
          <p><strong><%= mybooking.user.first_name %> has booked you</strong></p>
          <p><%= mybooking.start_date.day %>/<%= mybooking.start_date.month %> for <strong><%=  ((mybooking.end_date - mybooking.start_date) / 3600).round %> hours </strong> </p>
          <p><% if mybooking.status == nil %>
              <%= form_for(mybooking) do |f| %>
              <%= f.submit "Confirm", class: 'btn btn-outline-success btn-sm' %>
              <%= f.submit "Decline", class: 'btn btn-outline-danger btn-sm' %>
              <% end %>
              <% end %>
              <% if mybooking.status == true %>
              Booking Accepted ✔️
             <% elsif mybooking.status == false %>
              Booking cancelled ❌
             <% end %>
          </p>
        </div>
    </div>
    <% end %>
    <% end %>
    </div>
    </section>
    <section>
      <h2>Past</h2>
       <div class="cards-tab">
        <% @my_bookings.each do |mybooking| %>
        <% if mybooking.end_date < Time.now %>
        <div class="card-product tab" style="width: 300px">
            <img src="<%= mybooking.personality.image_url %>" />
            <div class="card-product-infos">
            <p><strong>Your past gig with <%= mybooking.user.first_name %></strong></p>
            <p><%= mybooking.start_date.day %>/<%= mybooking.start_date.month %> for <strong><%=  ((mybooking.end_date - mybooking.start_date) / 3600).round %> hours </strong> </p>
            <p><% if mybooking.status == nil %>
                <%= form_for(mybooking) do |f| %>
                <%= f.submit "Confirm", class: 'btn btn-outline-success btn-sm' %>
                <%= f.submit "Decline", class: 'btn btn-outline-danger btn-sm' %>
                <% end %>
                <% end %>
                <% if mybooking.status == true %>
                Booking Accepted ✔️
               <% elsif mybooking.status == false %>
                Booking cancelled ❌
               <% end %>
            </p>
          </div>
      </div>
      <% end %>
      <% end %>
      </div>
    </section>
  </div>
</div>

app/views/bookings/new.html.erb
 <div class="col-xs-12 col-sm-6">
  <div class="text-center">
    <%= simple_form_for [@personality, @booking] do |f| %>

      <div class="booking-card">
        <div >
        <%= f.input :start_date %>
        </div>
        <div>
        <%= f.input :end_date %>
        </div>
        <p> <strong>Total price: <%= @total_price %> €</strong></p>
        <%= f.submit "Book", class: "btn btn-primary"%>
      </div>

    <% end%>

  </div>
</div>

app/views/bookings/show.html.erb
<div class="rentals-container mt-5">
  <div class="card no-border mx-auto w-25" style="width: 18rem;">
  <img src="<%= @booking.personality.image_url %>" alt="" class='avatar-xlarge m-3 mt-4 mx-auto'>
  <h5 class="text-center mx-auto">  Booking with <%= @booking.personality.user.first_name %></h5>
  <p class="mx-auto"> <%= @booking.personality.name %> </p>
  <div class="px-4 pb-4 pt-0">
    <div class="d-flex justify-content-center text-center my-4">
      <div class="flex-item">
        <p class="mb-0" ><%= @booking.start_date.hour %>:<%= @booking.start_date.min %></p>
        <p class="date" style="color:black;"><%= @booking.start_date.day %>/<%= @booking.start_date.month %></p>
      </div>
      <div class='flex-item mx-3' ><strong> - </strong></div>
      <div class="flex-item">
        <p class="mb-0"><%= @booking.end_date.hour %>:<%= @booking.end_date.min %></p>
        <p class="date" style="color:black;"><%= @booking.end_date.day %>/<%= @booking.end_date.month %></p>
      </div>
    </div>
    <% if @booking.personality_reviews.count < 1 && @booking.end_date < Time.now %>
      <%= link_to "Leave a review", new_booking_personality_review_path(@booking), class: "btn btn-pink w-100" %>
    <% elsif @booking.end_date > Time.now %>
      <%= link_to 'Edit your booking', edit_booking_path, class: "btn btn-pink w-100" %>
        <p class="mt-4 border-top"></p>
        <div class='d-flex justify-content-between mt-3'>
          <h6>Total Price</h6>
          <h6><%= @booking.total_price %>€</h6>
        </div>
      <% else %>
      <p class="card-text ml-3">This booking has passed and you're all up to date with your reviews!</p>
    <% end %>
  </div>

  </div>
  <div class="mx-auto w-25">
    <p class="text-left pt-3 back-link"><%= link_to "Back", bookings_path %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnBatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('apple-icon-180x180.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/personalities/_listing.html.erb
<% personalities.each do |personality| %>
<div class="card-product">
  <img src= <%= personality.image_url %> />
    <div class="card-product-infos ">
      <h2 style='color:#eb535b;'> <%= personality.user.first_name  %> the <%=  link_to personality.name, personality_path(personality), style: 'color:#eb535b;' %></h2>
      <h3><%= personality.price_hour %>€/hour</h3>
      <!-- <p> <%= personality.description %> </p> -->
    </div>
</div>
<% end %>

app/views/personalities/edit.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center">
    <div class="card bg-light mb-3 rounded col-xm-12 col-5 ">
       <h1 class="card-title p-3">Edit - <%= @personality.name %></h1>
       <%= simple_form_for @personality do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price_hour %>
          <%= f.input :image_url %>
          <%= f.button :submit, class: "btn-primary" %>
          <%= f.button :button, "Cancel", type: "reset", class: "btn btn-danger ml-2" %>
        <% end %>
    </div>
    <div>
      <%= link_to "🗑",
                personality_path(@personality),
                method: :delete,
                data: { confirm: "Are you sure?" } %>
    </div>
  </div>
  <div>
  <%= link_to "Back", personalities_path, class: "btn btn-outline-primary"%>
  </div>
</div>

app/views/personalities/index.html.erb
<div class="banner" style="background-image: linear-gradient(to right, rgba(247, 140, 160, 0.7) 0%,rgba(249, 116, 143, 0.7) 19%, rgba(253, 134, 140, 0.7) 60%, rgba(254, 154, 139, 0.7) 100%), url(https://miro.medium.com/max/1400/1*btKhyXNSuB0yt2pwIFzA6Q.jpeg);">


  <div class="container">
    <h1 class="pb-0">The whole batch is up for rent</h1>
    <p class="pb-3">Discover skills you never dreamed they had</p>

    <div align="center">
      <%= form_tag personalities_path, method: :get, class: 'form-width w-100 flex d-flex justify-content-center' do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control w-50 search-bar",
          placeholder: "Find Dope Personalities by Name or Location"
        %>
        <%= submit_tag "🔎", class: "btn btn-pink-search" %>
      <% end %>
    </div>
      <div class="mouse_scroll">
          <div class="mouse">
            <div class="wheel"></div>
          </div>
          <div>
            <span class="m_scroll_arrows unu"></span>
            <span class="m_scroll_arrows doi"></span>
            <span class="m_scroll_arrows trei"></span>
          </div>
      </div>
  </div>
</div>

<div class="text-center mt-5 mx-auto">
  <h3 class= "sub-title">Check out some of the <strong id="orange-word">coolest people</strong> from Batch 448</h3>
</div>

<div class="btn-group ml-3">
  <label>
    <%= link_to "New", personalities_path(sort: :recent), method: "get", remote: true, class: "btn btn-light", type: 'radio'%>
  </label>
  <label>
    <%= link_to "Price", personalities_path(sort: :price), method: "get", remote: true, class: "btn btn-light", type: 'radio'%>
  </label>
  <label>
    <%= link_to "Name", personalities_path(sort: :name), method: "get", remote: true, class: "btn btn-light", type: 'radio'%>
  </label>
</div>



<div class="mb-5">
  <div class="px-4">
    <div class="row justify-content-center justify-content-lg-start" id="personalities-list">
      <%= render 'listing', personalities: @personalities %>
    </div>
  </div>
</div>



<div class="pb-3 mb-5"> </div>

app/views/personalities/index.js.erb
document.querySelector('#personalities-list').innerHTML = "<%= j render 'listing', personalities: @personalities %>"

app/views/personalities/new.html.erb
<div style="margin-bottom: 120px">
  <div class="rentals-container my-5">
    <div class="card no-border mx-auto " style="width: 27rem;">
      <div class="px-4 pb-4 pt-0">
        <h1 class="card-title">Add a new Personality</h1>
         <%= simple_form_for @personality do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :price_hour %>
            <%= f.input :image_url %>
            <%= f.button :submit, class: "btn btn-pink w-100" %>
          <% end %>
        <p class="text-center pt-3 back-link"><%= link_to "Back", personalities_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/personalities/show.html.erb
<div class="main-container">
  <div class="container w-100 pl-0 pt-4">
    <div class="container pl-0">
      <div class="d-flex flex-row mt-3">
        <div class='personality-img-container'>
          <img src="<%= @personality.image_url %>" alt="personality" class='avatar-xlarge'>
          <div class="edit-container">
          <p class="edit-text-center">
            <% if current_user == @personality.user %>
            <%= link_to 'Edit', edit_personality_path  %>
          <% end %>
          </p>
          </div>
        </div>
        <div class="align-self-center mx-3">
            <h6 class='user-name my-0'> <%= @personality.user.first_name %> </h6>
            <p class='personality-title my-0'> <%= @personality.name %> </p>
          </div>
        </div>
      </div>
    </div>
    <div class="container p-3">
      <div class="row">
        <div class="col-8 pl-0">
          <div class="border-top mr-5"></div>
          <h6 class="mt-4" style="font-weight: 600">About me</h6>
          <p class="mr-5" style="font-size: 0.9em"><%= @personality.description %></p>
          <div class="mt-5 border-top mr-5"></div>
          <h6 class="mt-4" style="font-weight: 600">Reviews</h6>
            <% if @personality.bookings.count == 0 %>
              <p style="font-size: 0.9em">This personality has no reviews yet. Be the first to review them!</p>
            <% end %>
          <div class="cards">
            <% @personality.bookings.each do |booking|  %>
              <% booking.personality_reviews.each do |personality_review|  %>

              <div class="pr-3">
              <img src="<%= personality_review.booking.user.image_url %>" alt="" class='avatar'>
              <i class="fas fa-star" style="font-size:10px; color: #eb535b"></i><span style="font-size:10px; font-weight:600"> <%= (personality_review.rating) %></span>
              <p class="mt-3" style="font-size: 0.7em"> <%= personality_review.comment %></p>
              </div>
             <% end %>

             <% end %>
          </div>
          <div class="mt-5 border-top mr-5"></div>
          <h6 class="mt-4" style="font-weight: 600">Location</h6>
          <div id="map"
             style="width: 100% !important; height: 100% !important;"
             data-markers="<%= @markers.to_json %>"
             data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
        <div class="col-4" style="height: 100vh;">
          <div class="booking-container p-3 sticky-top">

              <%= simple_form_for [@personality, @booking] do |f| %>
              <h4 class="price-hour pb-3" data-price="<%= @personality.price_hour %>"><%= @personality.price_hour %>€<span style="font-size: 12px"> /hour</span></h4>
              <h6>From</h6>
              <%= f.datetime_local_field :start_date, class: 'date-field' %>
              <h6>To</h6>
              <%= f.datetime_local_field :end_date, class: 'date-field' %>
              <%= f.submit "Book", class: "btn btn-pink w-100"%>

              <p class="mt-4 border-top"></p>
              <div class='d-flex justify-content-between mt-3'>
                <h6><strong>Total</strong></h6>
                <h6><strong id="total_price"><%= @booking.calc_total_price %></strong>€</h6>
              </div>
          <% end%>
          </div>

        </div>
      </div>

    </div>
     <!-- <%= link_to "Back", personalities_path, class: "btn btn-outline-primary" %> -->
  </div>
</div>

app/views/personality_reviews/new.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center">
    <div class="card bg-light mb-3 rounded col-xm-12 col-5" >
      <h1 class="card-title p-3">Add a new Review</h1>
       <%= simple_form_for [ @booking, @personality_review ] do |f| %>
          <%= f.input :comment %>
          <%= f.input :rating, collection: 0..5 %>
          <%= f.button :submit, class: "btn-primary" %>
          <%= f.button :button, "Cancel", type: "reset", class: "btn btn-danger ml-2" %>
        <% end %>
    </div>
  </div>
  <div>
  <%= link_to "Go back", personalities_path, class: "btn btn-outline-primary text-center" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <a href="#">About us</a>
    <a href="#">Terms</a>
    <a href="#">Privacy</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="<%= personalities_path %>">
    <%= image_tag "airbnb-batch.png", alt: "alttext" %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag current_user.image_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Add a Personality",new_personality_path, class: "dropdown-item" %>
              <%= link_to "Rentals", bookings_path, class: "dropdown-item" %>
              <%= link_to "Gigs", index_gigs_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "My Profile", user_path(current_user.id), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<h1>My Profile</h1>

<div class="m-5">
  <div class="row justify-content-center" >
    <div class="big-card-product" style="border-radius: 8px">
      <%= image_tag current_user.image_url%>
      <div class="big-card-product-infos">
        <%= link_to edit_user_registration_path do %>
          <i class="far fa-edit" style="color: #eb535b"></i>
        <% end %>
        <p><strong>Fullname:</strong></p>
        <h4><%= current_user.first_name%> <%= current_user.last_name%></h4>
        <p><strong>Language:</strong> <%= current_user.language%></p>
        <p><strong>City:</strong> <%= current_user.location%></p>
        <p><strong>Birthdate:</strong> <%= current_user.birthdate%></p>
        <p><strong>Phone:</strong> <%= current_user.phone%></p>
        <p><strong>Email:</strong> <%= current_user.email%></p>
        <p class="text-left pt-3 back-link"><%= link_to "Back", personalities_path %></p>
      </div>
    </div>
  </div>
</div>